const data=[{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "abdomen",
    "LayTerm": "belly",
    "Description": "",
    "ID": 224074,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "abdomen",
    "LayTerm": "procedure to burn or remove parts of <tissue> <an organ>",
    "Description": "",
    "ID": 224075,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "abrasions",
    "LayTerm": "grazes",
    "Description": "",
    "ID": 224076,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "abscess",
    "LayTerm": "a swollen area where pus has collected",
    "Description": "",
    "ID": 224077,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "absence seizure",
    "LayTerm": "see seizure, absence",
    "Description": "",
    "ID": 224078,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "acetylcholine",
    "LayTerm": "see neurotransmitter",
    "Description": "",
    "ID": 224079,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "acetylsalicylic acid",
    "LayTerm": "also known as aspirin",
    "Description": "",
    "ID": 224080,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "acid regurgitation",
    "LayTerm": "stomach acid flowing up into the mouth",
    "Description": "",
    "ID": 224081,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "acneiform",
    "LayTerm": "resembling acne",
    "Description": "",
    "ID": 224082,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "acromegaly",
    "LayTerm": "excessive growth particularly of the bones of the hands, feet and face caused by too much growth hormone <from the pituitary gland>",
    "Description": "",
    "ID": 224083,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "actinic keratoses",
    "LayTerm": "<precancerous,> abnormal skin growths caused by too much sunlight",
    "Description": "",
    "ID": 224084,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "acute",
    "LayTerm": "<short-lived> <sudden> <short-term>",
    "Description": "",
    "ID": 224085,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "acute coronary syndrome",
    "LayTerm": "<heart> conditions such as heart attack and unstable angina <(a type of severe chest pain)> <caused by blocked blood supply to parts of the heart>",
    "Description": "",
    "ID": 224086,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "acute systemic hypersensitivity reaction",
    "LayTerm": "see hypersensitivity reaction, acute systemic",
    "Description": "",
    "ID": 224087,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "adipocytes",
    "LayTerm": "fat cells",
    "Description": "",
    "ID": 224088,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "adjunct",
    "LayTerm": "add-on",
    "Description": "",
    "ID": 224089,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "adjuvant (vaccines)",
    "LayTerm": "a substance <such as aluminium> that increases the effect of the vaccine",
    "Description": "",
    "ID": 224090,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "advanced (cancer)",
    "LayTerm": "Consider has <started to> spread. Check definition for each cancer type carefully as this description may not always  apply",
    "Description": "",
    "ID": 224091,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "aggregate",
    "LayTerm": "stick together",
    "Description": "",
    "ID": 224092,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "agonist",
    "LayTerm": "a substance that attaches to a receptor (target) and triggers an effect",
    "Description": "",
    "ID": 224093,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "agranulocytosis",
    "LayTerm": "very low level of a type of white blood cell <called granulocytes><, which are important for fighting off infection>",
    "Description": "",
    "ID": 224094,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "akathisia",
    "LayTerm": "a constant urge to move",
    "Description": "",
    "ID": 224095,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "alcohol intoxication",
    "LayTerm": "Do not use: explain in text e.g. excessive alcohol consumption",
    "Description": "",
    "ID": 224096,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "alkaloids",
    "LayTerm": "substances that are naturally found in plants",
    "Description": "",
    "ID": 224097,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "allergen",
    "LayTerm": "a substance that causes an allergy",
    "Description": "",
    "ID": 224098,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "allergen challenge",
    "LayTerm": "a test to measure a patient’s reaction to a defined dose of an allergen (the substance that they are allergic to)",
    "Description": "",
    "ID": 224099,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "allergic rhinitis",
    "LayTerm": "see rhinitis, allergic",
    "Description": "",
    "ID": 224100,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "allotransplantation",
    "LayTerm": "when a patient receives cells, tissues or organs from a donor",
    "Description": "",
    "ID": 224101,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "alopecia",
    "LayTerm": "Substitute with hair loss",
    "Description": "",
    "ID": 224102,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "alveolitis, allergic",
    "LayTerm": "see pneumonitis, hypersensitivity",
    "Description": "",
    "ID": 224103,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "ambulatory",
    "LayTerm": "able to walk Avoid term where possible",
    "Description": "",
    "ID": 224104,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "amnesia",
    "LayTerm": "Substitute with memory loss",
    "Description": "",
    "ID": 224105,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "amyloidosis",
    "LayTerm": "build-up in the body of amyloid, an abnormal protein <which can damage organs>",
    "Description": "",
    "ID": 224106,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaemia",
    "LayTerm": "<low red blood cell counts> <low levels of haemoglobin> <which can cause tiredness and pale skin>",
    "Description": "",
    "ID": 224107,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaemia, aplastic",
    "LayTerm": "when bone marrow stops producing new blood cells <causing tiredness, lower ability to fight infection and uncontrolled bleeding>",
    "Description": "",
    "ID": 224108,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaemia, haemolytic",
    "LayTerm": "excessive breakdown of red blood cells <causing tiredness and pale skin>",
    "Description": "",
    "ID": 224109,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaesthetic",
    "LayTerm": "a medicine <which blocks sensation> used to prevent pain and discomfort\r\n<during surgery and medical procedures>",
    "Description": "",
    "ID": 224110,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaesthetic block",
    "LayTerm": "see nerve block",
    "Description": "",
    "ID": 224111,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaesthetic, general",
    "LayTerm": "a medicine that can be used to prevent pain by making the patient unconscious",
    "Description": "",
    "ID": 224112,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaesthetic, local",
    "LayTerm": "a medicine that blocks out sensation used to prevent pain in a part of the body\r\n<during surgery or other medical procedure>",
    "Description": "",
    "ID": 224113,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaesthetist",
    "LayTerm": "a doctor specialised in anaesthesia",
    "Description": "",
    "ID": 224114,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "analgesic",
    "LayTerm": "painkiller",
    "Description": "",
    "ID": 224115,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "analgesic, intraspinal",
    "LayTerm": "painkilling medicine injected into the spine",
    "Description": "",
    "ID": 224116,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaphylactic reaction (shock)",
    "LayTerm": "see anaphylaxis",
    "Description": "",
    "ID": 224117,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaphylactoid reaction",
    "LayTerm": "sudden, severe allergic reaction <with breathing difficulty, swelling, lightheadedness, fast heartbeat, sweating and loss of consciousness>",
    "Description": "",
    "ID": 224118,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "anaphylaxis",
    "LayTerm": "sudden, severe allergic reaction <with breathing difficulty, swelling, lightheadedness, fast heartbeat, sweating and loss of consciousness>",
    "Description": "",
    "ID": 224119,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "aneurysm",
    "LayTerm": "bulging and weakening of blood vessel <wall>",
    "Description": "",
    "ID": 224120,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
},
{
    "GlossaryTemplateID": 3,
    "GlossaryTemplate": "MMS Lay Scientific Terms - EMA",
    "ClinicalTerm": "angina",
    "LayTerm": "see angina pectoris",
    "Description": "",
    "ID": 224121,
    "CreatedBy": "",
    "CreatedDate": "",
    "UpdatedBy": "",
    "UpdatedDate": "",
    "Status": "1"
}]


export {data};